<a href="https://colab.research.google.com/github/evasseva/evasseva/blob/main/%EC%98%81%ED%99%94%EB%A6%AC%EB%B7%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras. utils import to_categorical

from numpy import array

In [4]:
# 텍스트 리뷰 자료 지정

docs = ["너무 재밌네요", "최고예요", "참 잘 만든 영화예요", "추천하고 싶은 영화입니다", "한번 더 보고싶네요", "글쎄요", "별로예요", "생각보다 지루하네요",
        "연기가 어색해요", "재미없어요"]

In [5]:
# 긍정리뷰는 1, 부정리뷰는 0으로 클래스 지정

classes = array([1,1,1,1,1,0,0,0,0,0])

In [6]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n", x)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [7]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어줍니다.
padded_x = pad_sequences(x, 4)
print("\n패딩결과:\n", padded_x)

# 임베딩에 입력될 단어의 수 지정
word_size = len(token.word_index) + 1


패딩결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [8]:
# 단어 임베딩 포함 딥러닝 모델 만든 후 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 1s 866ms/step - loss: 0.6871 - accuracy: 0.7000
Epoch 2/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6853 - accuracy: 0.7000
Epoch 3/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6834 - accuracy: 0.9000
Epoch 4/20
1/1 [===============